image: Visual Studio 2017

version: 0.6.1.{build}

skip_tags: true

skip_branch_with_pr: false

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  _zip: '%APPVEYOR_BUILD_FOLDER%\HaloOnline-%APPVEYOR_BUILD_VERSION%.zip'
  _zipD: '%APPVEYOR_BUILD_FOLDER%\HaloOnline-%APPVEYOR_BUILD_VERSION%-debug.zip'
  _7z: 7z -tzip a %_zip% -r -x!*.config -x!*.exp -x!*.lib -x!*.pdb
  _7zD: 7z -tzip a %_zipD% -r -x!*.config -x!*.exp -x!*.lib -x!*.ilk
  _vInfo: '%APPVEYOR_BUILD_FOLDER%\HaloOnline\Source\Utils\VersionInfo.cpp'

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\HaloOnline

shallow_clone: true

build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" /nologo /m:2 /p:Configuration="Release" /p:Platform="Win32" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "%APPVEYOR_BUILD_FOLDER%\HaloOnline.sln"

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" /nologo /m:2 /p:Configuration="Debug" /p:Platform="Win32" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "%APPVEYOR_BUILD_FOLDER%\HaloOnline.sln"

before_build:
- cmd: >-
    CD %APPVEYOR_BUILD_FOLDER%

    git clone https://github.com/scooterpsu/medalPack.git .\dist\mods\medals\default

    RM -rf .\dist\mods\medals\default\.git

- ps: (Get-Content "$env:_vInfo") -replace 'V\(\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\s*\)', "V(`$1, `$2, `$3, $env:APPVEYOR_BUILD_NUMBER)" | Out-File "$env:_vInfo"

after_build:
- cmd: >-
    CD %APPVEYOR_BUILD_FOLDER%\dist\

    echo D|xcopy /e /y ..\Release\* .\

    appveyor PushArtifact .\haloonline.dll

    %_7z% *

    appveyor PushArtifact %_zip%
    
    del %_zip%
    
    echo D|xcopy /e /y ..\Debug\* .\

    %_7zD% *

    appveyor PushArtifact %_zipD%

    move haloonline.dll haloonline-debug.dll

    appveyor PushArtifact haloonline-debug.dll

    move haloonline.pdb haloonline-debug.pdb

    appveyor PushArtifact haloonline-debug.pdb
